SELECT
 D.NAME AS DEPARTMENT,
 E.NAME AS EMPLOYEE,
 E.SALARY AS SALARY
 FROM EMPLOYEE E
 JOIN DEPARTMENT D
 ON E.DEPARTMENTID=D.ID
 WHERE SALARY=
 (
    SELECT MAX(SALARY) FROM EMPLOYEE E
    WHERE E.DEPARTMENTID=D.ID
 )